categories = {
            -- Crafted items
            {'minecraft:scaffolding'
            'minecraft:torch'
            'minecraft:glass'
            'minecraft:dirt'
            'minecraft:oak_slab'
            'minecraft:paper'
            'minecraft:deepslate_tile_stairs'
            'minecraft:cobbled_deepslate_wall'
            'minecraft:deepslate_brick_slab'
            'minecraft:cobblestone_wall'
            'minecraft:yellow_dye'
            'minecraft:oak_stairs'
            'minecraft:rail'
            'minecraft:cobblestone_slab'
            'minecraft:deepslate_brick_stairs'
            'minecraft:ladder'
            'minecraft:piston'
            'minecraft:deepslate_tile_slab'
            'minecraft:glass_pane'
            'minecraft:oak_fence'
            'minecraft:observer'
            'minecraft:purple_stained_glass'
            'minecraft:cobbled_deepslate_stairs'
            'minecraft:hopper'
            'minecraft:gray_dye'
            'minecraft:item_frame'
            'minecraft:oak_pressure_plate'
            'create:framed_glass_door'
            'minecraft:redstone_lamp'
            'minecraft:lever'
            'create:copycat_panel'
            'minecraft:white_carpet'
            'minecraft:oak_boat'
            'minecraft:crafting_table'
            'minecraft:blue_dye'
            'minecraft:oak_door'
            'minecraft:nether_brick_fence'
            'minecraft:daylight_detector'
            'minecraft:stone_brick_slab'
            'create:framed_glass'
            'minecraft:stone_slab'
            'minecraft:dispenser'
            'create:copycat_step'
            'minecraft:stone_bricks'
            'minecraft:smooth_stone'},

            -- Dirt/deepslate
            {"minecraft:dirt",
            "minecraft:cobbled_deepslate"},

            --Tools
            {"minecraft:wooden_axe",
            "minecraft:wooden_pickaxe",
            "minecraft:wooden_sword",
            "minecraft:wooden_shovel",
            "minecraft:wooden_hoe",

            "minecraft:stone_axe",
            "minecraft:stone_pickaxe",
            "minecraft:stone_sword",
            "minecraft:stone_shovel",
            "minecraft:stone_hoe",

            "minecraft:iron_axe",
            "minecraft:iron_pickaxe",
            "minecraft:iron_sword",
            "minecraft:iron_shovel",
            "minecraft:iron_hoe",
            "minecraft:iron_helmet",
            "minecraft:iron_chestplate",
            "minecraft:iron_leggings",
            "minecraft:iron_boots",

            "minecraft:golden_axe",
            "minecraft:golden_pickaxe",
            "minecraft:golden_sword",
            "minecraft:golden_shovel",
            "minecraft:golden_hoe",
            "minecraft:golden_helmet",
            "minecraft:golden_chestplate",
            "minecraft:golden_leggings",
            "minecraft:golden_boots",

            "minecraft:diamond_axe",
            "minecraft:diamond_pickaxe",
            "minecraft:diamond_sword",
            "minecraft:diamond_shovel",
            "minecraft:diamond_hoe",
            "minecraft:diamond_helmet",
            "minecraft:diamond_chestplate",
            "minecraft:diamond_leggings",
            "minecraft:diamond_boots",

            "minecraft:netherite_axe",
            "minecraft:netherite_pickaxe",
            "minecraft:netherite_sword",
            "minecraft:netherite_shovel",
            "minecraft:netherite_hoe",
            "minecraft:netherite_helmet",
            "minecraft:netherite_chestplate",
            "minecraft:netherite_leggings",
            "minecraft:netherite_boots",

            "minecraft:flint_and_steel",
            "minecraft:bow",
            "minecraft:crossbow",
            "minecraft:fishing_rod",
            "minecraft:carrot_on_a_stick",
            "minecraft:warped_fungus_on_a_stick",
            "minecraft:shears",
            "minecraft:shield",
            "minecraft:brush",
            "minecraft:spyglass",
            "minecraft:compass",
            "minecraft:recovery_compass",
            "minecraft:clock",
            "minecraft:lead",
            "minecraft:name_tag",
            "minecraft:elytra",

            "create:wrench",
            "create:goggles"},

            --Plants/farming
            {"minecraft:wheat",
            "minecraft:wheat_seeds",
            "minecraft:carrot",
            "minecraft:potato",
            "minecraft:beetroot",
            "minecraft:beetroot_seeds",
            "minecraft:melon",
            "minecraft:melon_slice",
            "minecraft:melon_seeds",
            "minecraft:pumpkin",
            "minecraft:pumpkin_seeds",
            "minecraft:sugar_cane",
            "minecraft:cactus",
            "minecraft:bamboo",
            "minecraft:kelp",
            "minecraft:dried_kelp",
            "minecraft:sea_pickle",
            "minecraft:cocoa_beans",
            "minecraft:nether_wart",
            "minecraft:warped_fungus",
            "minecraft:crimson_fungus",
            "minecraft:brown_mushroom",
            "minecraft:red_mushroom",
            "minecraft:apple",
            "minecraft:sweet_berries",
            "minecraft:glow_berries",
            "minecraft:lily_pad",
            "minecraft:vine",
            "minecraft:weeping_vines",
            "minecraft:twisting_vines",
            "minecraft:big_dripleaf",
            "minecraft:small_dripleaf",
            "minecraft:flowering_azalea",
            "minecraft:azalea",
            "minecraft:spruce_sapling",
            "minecraft:acacia_sapling",
            "minecraft:oak_sapling",
            "minecraft:birch_sapling",
            "minecraft:dark_oak_sapling",
            "minecraft:moss_block",
            "minecraft:moss_carpet"},

            --Mob drops
            {"minecraft:egg",
            "minecraft:leather",
            "minecraft:rabbit_hide",
            "minecraft:rabbit_foot",
            "minecraft:feather",
            "minecraft:bone",
            "minecraft:bone_meal",
            "minecraft:ink_sac",
            "minecraft:glow_ink_sac",
            "minecraft:string",
            "minecraft:spider_eye",
            "minecraft:fermented_spider_eye",
            "minecraft:gunpowder",
            "minecraft:slime_ball",
            "minecraft:rotten_flesh",
            "minecraft:ender_pearl",
            "minecraft:blaze_rod",
            "minecraft:blaze_powder",
            "minecraft:magma_cream",
            "minecraft:ghast_tear",
            "minecraft:shulker_shell",
            "minecraft:phantom_membrane",
            "minecraft:prismarine_shard",
            "minecraft:prismarine_crystals",
            "minecraft:nautilus_shell",
            "minecraft:scute",
            "minecraft:echo_shard",
            "minecraft:heart_of_the_sea",
            "minecraft:beef",
            "minecraft:cooked_beef",
            "minecraft:porkchop",
            "minecraft:cooked_porkchop",
            "minecraft:chicken",
            "minecraft:cooked_chicken",
            "minecraft:mutton",
            "minecraft:cooked_mutton",
            "minecraft:rabbit",
            "minecraft:cooked_rabbit",
            "minecraft:cod",
            "minecraft:cooked_cod",
            "minecraft:salmon",
            "minecraft:cooked_salmon",
            "minecraft:tropical_fish",
            "minecraft:pufferfish",
            "minecraft:milk_bucket",
            "minecraft:honeycomb",
            "minecraft:honey_bottle"},

            -- Ores/Ingots
            {"minecraft:coal",
            "minecraft:raw_iron",
            "minecraft:raw_copper",
            "minecraft:raw_gold",
            "minecraft:iron_ingot",
            "minecraft:copper_ingot",
            "minecraft:gold_ingot",
            "minecraft:iron_nugget",
            "minecraft:copper_nugget",
            "minecraft:gold_nugget",
            "minecraft:diamond",
            "minecraft:emerald",
            "minecraft:lapis_lazuli",
            "minecraft:redstone",
            "minecraft:quartz",
            "minecraft:netherite_scrap",
            "minecraft:netherite_ingot",

            "create:brass_ingot",
            "create:brass_nugget",
            "create:raw_zinc",
            "create:zinc_ingot",
            "create:zinc_nugget"},

            -- Rocks
            {"minecraft:coarse_dirt",
            "minecraft:rooted_dirt",
            "minecraft:grass_block",
            "minecraft:podzol",
            "minecraft:mycelium",
            "minecraft:deepslate",
            "minecraft:stone",
            "minecraft:cobblestone",
            "minecraft:mossy_cobblestone",
            "minecraft:andesite",
            "minecraft:diorite",
            "minecraft:granite",
            "minecraft:tuff",
            "minecraft:calcite",
            "minecraft:dripstone_block",
            "minecraft:pointed_dripstone",
            "minecraft:basalt",
            "minecraft:smooth_basalt",
            "minecraft:blackstone",
            "minecraft:polished_blackstone",
            "minecraft:netherrack",
            "minecraft:end_stone",
            "minecraft:obsidian",
            "minecraft:crying_obsidian",
            "minecraft:sand",
            "minecraft:red_sand",
            "minecraft:gravel",
            "minecraft:clay_ball",
            "minecraft:clay",
            "minecraft:flint",
            "minecraft:coal_ore",
            "minecraft:deepslate_coal_ore",
            "minecraft:iron_ore",
            "minecraft:deepslate_iron_ore",
            "minecraft:copper_ore",
            "minecraft:deepslate_copper_ore",
            "minecraft:gold_ore",
            "minecraft:deepslate_gold_ore",
            "minecraft:redstone_ore",
            "minecraft:deepslate_redstone_ore",
            "minecraft:emerald_ore",
            "minecraft:deepslate_emerald_ore",
            "minecraft:lapis_ore",
            "minecraft:deepslate_lapis_ore",
            "minecraft:diamond_ore",
            "minecraft:deepslate_diamond_ore",
            "minecraft:nether_gold_ore",
            "minecraft:nether_quartz_ore",
            "minecraft:ancient_debris"},

            -- Create mod
            {'minecraft:andesite'
            'create:cogwheel'
            'create:zinc_ingot'
            'create:fluid_tank'
            'create:brass_casing'
            'create:brass_ingot'
            'create:andesite_alloy'
            'create:golden_sheet'
            'create:zinc_nugget'
            'create:andesite_casing'
            'create:shaft'
            'create:polished_rose_quartz'
            'create:chute'
            'create:copycat_step'
            'create:encased_chain_drive'
            'create:fluid_pipe'
            'create:brass_sheet'
            'create:mechanical_saw'
            'create:copper_casing'
            'create:copper_sheet'
            'create:adjustable_chain_gearshift'
            'create:item_drain'
            'create:mechanical_bearing'
            'create:hand_crank'
            'create:potato_cannon'
            'create:sand_paper'
            'create:furnace_minecart_contraption'
            'create:large_cogwheel'
            'create:smart_chute'
            'create:gearshift'
            'create:depot'
            'create:super_glue'
            'create:track_station'
            'create:speedometer'
            'create:copycat_panel'
            'create:goggles'
            'create:wrench'
            'create:cart_assembler'
            'create:blaze_burner'},

            -- Food
            {"minecraft:bread",
            "minecraft:cookie",
            "minecraft:cake",
            "minecraft:pumpkin_pie",
            "minecraft:golden_carrot",
            "minecraft:beetroot_soup",
            "minecraft:mushroom_stew",
            "minecraft:rabbit_stew",
            "minecraft:suspicious_stew",
            "minecraft:dried_kelp",
            "minecraft:chorus_fruit",
            "minecraft:beef",
            "minecraft:cooked_beef",
            "minecraft:porkchop",
            "minecraft:cooked_porkchop",
            "minecraft:chicken",
            "minecraft:cooked_chicken",
            "minecraft:mutton",
            "minecraft:cooked_mutton",
            "minecraft:rabbit",
            "minecraft:cooked_rabbit",
            "minecraft:cod",
            "minecraft:cooked_cod",
            "minecraft:salmon",
            "minecraft:cooked_salmon",
            "minecraft:tropical_fish",
            "minecraft:pufferfish"},

            -- Redstone
            {"minecraft:redstone",
            "minecraft:redstone_torch",
            "minecraft:repeater",
            "minecraft:comparator",
            "minecraft:piston",
            "minecraft:sticky_piston",
            "minecraft:observer",
            "minecraft:hopper",
            "minecraft:dropper",
            "minecraft:dispenser",
            "minecraft:lever",
            "minecraft:stone_button",
            "minecraft:target",
            "minecraft:daylight_detector",
            "minecraft:tripwire_hook"},

            -- Nether
            {"minecraft:netherrack",
            "minecraft:soul_sand",
            "minecraft:soul_soil",
            "minecraft:nether_brick",
            "minecraft:nether_bricks",
            "minecraft:netherite_scrap",
            "minecraft:netherite_ingot",
            "minecraft:glowstone_dust",
            "minecraft:glowstone",
            "minecraft:quartz",
            "minecraft:quartz_block",
            "minecraft:blaze_rod",
            "minecraft:ghast_tear",
            "minecraft:magma_cream",
            "minecraft:obsidian",
            "minecraft:crying_obsidian",
            "minecraft:end_stone",
            "minecraft:end_stone_bricks",
            "minecraft:chorus_fruit",
            "minecraft:popped_chorus_fruit",
            "minecraft:ender_pearl",
            "minecraft:shulker_shell",
            "minecraft:dragon_breath"},

            -- Transport/containers
            {"minecraft:rail",
            "minecraft:powered_rail",
            "minecraft:detector_rail",
            "minecraft:activator_rail",
            "minecraft:minecart",
            "minecraft:chest_minecart",
            "minecraft:hopper_minecart",
            "minecraft:furnace_minecart",
            "minecraft:oak_boat",
            "minecraft:oak_chest_boat",
            "minecraft:chest",
            "minecraft:trapped_chest",
            "minecraft:barrel",
            "minecraft:shulker_box",
            "minecraft:hopper",
            "minecraft:bucket",
            "minecraft:water_bucket",
            "minecraft:lava_bucket",
            "minecraft:powder_snow_bucket",
            "minecraft:milk_bucket",
            "minecraft:glass_bottle",
            "minecraft:bundle"},

            -- Non minecraft
            {"create:whisk",
            "create:propeller"}
}

return categories
